### ISSUE TITLE
Add cycles

### ISSUE THREAD

**Issue by k80** [Force-Fitness/FFPT#8]
aka, Periodization
[Force Fitness Periodization.rtfd.zip](https://github.com/Force-Fitness/FFPT/files/75093/Force.Fitness.Periodization.rtfd.zip)

**Comment by k80** [comment]
@Rcon40, I'm thinking the URL "/periodization" and the nav/menu item, "Training with Purpose" should maybe be swapped for each other, or something else all together? I'm concerned people won't know what "Periodization" is to click on it, but I feel like "Training with Purpose" is a bit long in the current formatting of the menu, but maybe the rest of the nav is what needs to change (I could move stuff [Classes, Issue #7 and Resources, Issue #6 ] to the footer??

**Comment by Rcon40** [comment]
http://www.businessinsider.com/the-10-best-logo-changes-of-2015-2015-12

Thought you might appreciate this.
It also mentions the agencies (wink wink)

**Comment by Rcon40** [comment]
For the Cycle image, (the chart)

can you add  " Copyright © 2015 Force Fitness Personal Training, All Rights
Reserved. " to the bottom?

Also, or the Movement chart, I need to reorder them. It should be Mobility,
Flexibility, Stability. Leave the colors as is, the words are just out of
order.

**Comment by Rcon40** [comment]
the movement section on the chart**
